services:
  backend:
    build: .
    ports:
      - '8080:8080'
    environment:
      - URL_BACKEND=${URL_BACKEND}
      - URL_FRONTEND=${URL_FRONTEND}
      - URI_MONGODB=${URI_MONGODB}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_EMAIL_CONFIRM_TOKEN_SECRET=${JWT_EMAIL_CONFIRM_TOKEN_SECRET}
      - JWT_PASSWORD_RESET_TOKEN_SECRET=${JWT_PASSWORD_RESET_TOKEN_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM=${RESEND_FROM}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - tailsync-network
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tailsync
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tailsync-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  tailsync-network:
    name: tailsync-network
    driver: bridge
